
const LIQUIDATE_UPDATE_POOL  = "LIQUIDATE_UPDATE_POOL";
const LIQUIDATE_UPDATE_INPUT = "LIQUIDATE_UPDATE_INPUT";
const LIQUIDATE_UPDATE_OUTPUTS = "LIQUIDATE_UPDATE_OUTPUTS";
const LIQUIDATE_DISABLE = "LIQUIDATE_DISABLE";
const LIQUIDATE_ENABLE = "LIQUIDATE_ENABLE";
const LIQUIDATE_APPROVE_OR_REJECT = "LIQUIDATE_APPROVE_OR_REJECT";

const INVEST_UPDATE_POOL  = "INVEST_UPDATE_POOL";
const INVEST_UPDATE_INPUT = "INVEST_UPDATE_INPUT";
const INVEST_UPDATE_OUTPUTS = "INVEST_UPDATE_OUTPUTS";
const INVEST_DISABLE = "INVEST_DISABLE";
const INVEST_ENABLE = "INVEST_ENABLE";
const INVEST_APPROVE_OR_REJECT = "INVEST_APPROVE_OR_REJECT";
const INVEST_UPDATE_ALERT_MESSAGE = "INVEST_UPDATE_ALERT_MESSAGE"

const CONVERT_UPDATE_OUTPUT = "CONVERT_UPDATE_OUTPUT";
const CONVERT_UPDATE_INPUT = "CONVERT_UPDATE_INPUT";
const CONVERT_UPDATE_FROM_TOKEN = "CONVERT_UPDATE_FROM_TOKEN";
const CONVERT_UPDATE_TO_TOKEN = "CONVERT_UPDATE_TO_TOKEN";
const CONVERT_DISABLE = "CONVERT_DISABLE";
const CONVERT_ENABLE = "CONVERT_ENABLE";
const CONVERT_APPROVE_OR_REJECT = "CONVERT_APPROVE_OR_REJECT";
const CONVERT_UPDATE_ALERT_MESSAGE = "CONVERT_UPDATE_ALERT_MESSAGE";

const WALLET_INSTALL = "WALLET_INSTALL";
const WALLET_CONNECT = "WALLET_CONNECT";
const WALLET_CONNECTED = "WALLET_CONNECTED";
const WALLET_DENIED = "WALLET_DENIED";

export {
	
	LIQUIDATE_UPDATE_POOL,
	LIQUIDATE_UPDATE_INPUT,
	LIQUIDATE_UPDATE_OUTPUTS,
	LIQUIDATE_DISABLE,
	LIQUIDATE_ENABLE,
	LIQUIDATE_APPROVE_OR_REJECT,

	INVEST_UPDATE_POOL,
	INVEST_UPDATE_INPUT,
	INVEST_UPDATE_OUTPUTS,
	INVEST_DISABLE,
	INVEST_ENABLE,
	INVEST_APPROVE_OR_REJECT,
	INVEST_UPDATE_ALERT_MESSAGE,

	CONVERT_UPDATE_OUTPUT,
	CONVERT_UPDATE_INPUT,
	CONVERT_UPDATE_FROM_TOKEN,
	CONVERT_UPDATE_TO_TOKEN,
	CONVERT_UPDATE_ALERT_MESSAGE,

	WALLET_INSTALL,
	WALLET_CONNECT,
	WALLET_CONNECTED,
	WALLET_DENIED,
	CONVERT_ENABLE,
	CONVERT_DISABLE,
	CONVERT_APPROVE_OR_REJECT
}